function [state, I_influx] = simulate_single_step(...
    current_state, ...
    params, ...
    delta_t...
    )

    state = current_state;

    state.S = current_state.S + delta_t * (0 ...
        - current_state.S * params.beta * current_state.I ... %* params(10) ...
        + current_state.R * params.omega ...
        );

    state.I = current_state.I + delta_t * (0 ...
        + current_state.S * params.beta * current_state.I ... %* params(10) ...
        - current_state.I * params.gamma ...
        );

    I_influx = delta_t * (current_state.S * params.beta * current_state.I );%* params(10));

    state.R = current_state.R + delta_t * (0 ...
        + current_state.I * params.gamma ...
        - current_state.R * params.omega ...
        );
end